/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 9: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 10: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
/var/spool/pbs/mom_priv/jobs/2121.humgendiv.SC: line 13: /output.txt: Permission denied
cat: /output.txt: No such file or directory
